### ISSUE TITLE
MA3 not updating x touch

### ISSUE THREAD

**Issue by Dogo69Dog** [xxpasixx/pam-osc#1] opened 2024-02-24 20:47 UTC
I think i have everything setup the way it should be but i move a fader on ma3 and my x touch doesent move. Open stage control seems to be setup properly because when i move a fader it sees im moving it but ma3 doesent see that fader moving. Below is the config i have. Btw im using the loopback ma interface. 
![Screenshot 2024-02-24 at 3 46 30 PM](https://github.com/xxpasixx/pam-osc/assets/143454412/7f89d897-7595-4cd6-b975-e3228a6e96b6)
![Screenshot 2024-02-24 at 3 46 39 PM](https://github.com/xxpasixx/pam-osc/assets/143454412/11924b7d-243d-4d16-b1e1-f35bdd9803ff)
![Screenshot 2024-02-24 at 3 46 55 PM](https://github.com/xxpasixx/pam-osc/assets/143454412/408d5028-5408-4255-beb2-67ba5d58ea9a)
![Screenshot 2024-02-24 at 3 47 08 PM](https://github.com/xxpasixx/pam-osc/assets/143454412/136584ee-3137-4195-897a-b0bf9fe113a2)

**Comment by xxpasixx** [comment] 2024-03-16 18:50
Hey Dogo69Dog,
sorry for the late response, i was on Vaccation for a vew Weeks.
i saw on the other Issue, that you figgured it out using Chataigne. Great :)

i still try to help you out 👍 
the GrandMA3 config looks good and also the configuration in the OSC gui looks good. I think the Issue is the ip in the config file. I think you have to send it directly to the "127.0.0.1", the Broadcast IP .255 is not working i think.
Its not that clear in the docu, i will update it.

Let me knew if you want to try it again, or otherwise if we could close the issue 👌 

Thanks for testing 😄

**Comment by Dogo69Dog** [comment] 2024-03-16 19:48
Yea i kind of got it working in chatagine but in the end i would prefer to get it working with your plugin. Let me go ahead and try again and see how it goes.

**Comment by Dogo69Dog** [comment] 2024-03-16 19:56
Ok so for some reason i cant get ma3 to even get any input now, i see open stage control is getting ifo thought. I sent a screenshot below

![image](https://github.com/xxpasixx/pam-osc/assets/143454412/450795c0-01c6-442b-a6b5-cad7561d9b69)

**Comment by xxpasixx** [comment] 2024-03-16 19:59
hm... okay.
would you like to jump on a quick call with me ? i think that would be the easyest.
Just send me an Email with your Discord or so to: info@pam-lights.de

**Comment by Dogo69Dog** [comment] 2024-03-16 20:00
Sure, sending now

**Comment by xxpasixx** [comment] 2024-03-16 20:41
On Call updated all ip's and created a Session in MA. It's working now 😉

**Closed by xxpasixx** 2024-03-16 20:41 UTC
